import bcrypt from 'bcryptjs';
const data = {
	users: [
		{
			name: 'Jemaica',
			email: 'admin@gmail.com',
			password: bcrypt.hashSync('1234', 8),
			isAdmin: true,
		},
		{
			name: 'Russel',
			email: 'russ_user@gmail.com',
			password: bcrypt.hashSync('U1234567', 8),
			isAdmin: false,
		},
	],
	products: [
		{
			price: 549,
			countInStock: 37,
			rating: 3.5,
			numReviews: 10,
			name: 'Alaska',
			image: '/images/alaska.jpg',
			brand: 'Purex',
			category: 'Canned Goods',
			description: '4.43L',
			__v: 0,
		},
		{
			price: 249,
			countInStock: 80,
			rating: 4.1,
			numReviews: 10,
			name: 'Cereal',
			image: '/images/cereal.jpg',
			brand: 'No Brand',
			category: 'Breakfast',
			description: '198g',
			__v: 0,
		},
		{
			price: 59,
			countInStock: 186,
			rating: 4.8,
			numReviews: 17,
			name: 'Kitkat',
			image: '/images/kitkat.jpg',
			brand: 'Nestle',
			category: 'Snacks',
			description: '198g',
			__v: 0,
		},
		{
			price: 239,
			countInStock: 34,
			rating: 4.5,
			numReviews: 14,
			name: 'Tender Juicy Hotdog',
			image: '/images/hotdog.jpg',
			brand: 'Tender Juicy',
			category: 'Frozen',
			description: '16pcs',
			__v: 0,
		},
		{
			price: 69,
			countInStock: 80,
			rating: 4.5,
			numReviews: 10,
			name: 'Chicken',
			image: '/images/chicken.jpg',
			brand: 'No Brand',
			category: 'Household',
			description: '1kg',
			__v: 0,
		},
		{
			price: 614,
			countInStock: 21,
			rating: 4.5,
			numReviews: 15,
			name: 'Yakult',
			image: '/images/yakult.jpg',
			brand: 'Super-tie',
			category: 'Beverage',
			description: '6pcs',
			__v: 0,
		},
	],
};
export default data;
