const data = {
	products: [
		{
			id: 1,
			price: 549,
			countInStock: 37,
			rating: '0',
			numReview: '0',
			name: 'Alaska',
			image: './images/alaska.jpg',
			brand: 'Purex',
			category: 'Canned Goods',
			description: '4.43L',
			__v: 0,
		},
		{
			id: 2,
			price: 249,
			countInStock: 80,
			rating: '0',
			numReview: '0',
			name: 'Cereal',
			image: './images/cereal.jpg',
			brand: 'No Brand',
			category: 'Breakfast',
			description: '198g',
			__v: 0,
		},
		{
			id: 3,
			price: 59,
			countInStock: 186,
			rating: '0',
			numReview: '0',
			name: 'Kitkat',
			image: './images/kitkat.jpg',
			brand: 'Nestle',
			category: 'Snacks',
			description: '198g',
			__v: 0,
		},
		{
			id: 4,
			price: 239,
			countInStock: 34,
			rating: '0',
			numReview: '0',
			name: 'Tender Juicy Hotdog',
			image: './images/hotdog.jpg',
			brand: 'Tender Juicy',
			category: 'Frozen',
			description: '16pcs',
			__v: 0,
		},
		{
			id: 5,
			price: 69,
			countInStock: 80,
			rating: '0',
			numReview: '0',
			name: 'Chicken',
			image: './images/chicken.jpg',
			brand: 'No Brand',
			category: 'Household',
			description: '1kg',
			__v: 0,
		},
		{
			id: 6,
			price: 614,
			countInStock: 21,
			rating: '0',
			numReview: '0',
			name: 'Yakult',
			image: './images/yakult.jpg',
			brand: 'Super-tie',
			category: 'Beverage',
			description: '6pcs',
			__v: 0,
		},
	],
};
export default data;
